### ISSUE TITLE
Rumble will not work

### ISSUE THREAD

**Issue by xperia64** [brownan/Gamecube-N64-Controller#1]
Ok so after about 4 hours, i got the wires in the right place and everything seemed to be working fine except for rumble. i tried changing bool rumble to true but that did not seem to work. could it be the part about "// The last bit is rumble, flip it to rumble"? 
Also, i used the second ground port on the digital I/O side for the gamecube cable "#3" ground and the n64 ground in your diagrams. Thank you for your time.

**Comment by NicoHood** [comment]
brownan i think you can close this issue
